#!/bin/bash

###
# 强制踢出空闲超过半小时的人
###

function uniq() {
	awk '{!seen[$0]++};END{for(i in seen) print i}'
}

OUTDATED=($(idle 1800 | uniq))

for N in "${OUTDATED[@]}"
do
	echo "kick $N" >&2
	kick $N "你因为[闲置30分钟]被系统踢出。"
done

